export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SUPPORT = 'SUPPORT',
}

export enum Permission {
  VIEW_JOBS = 'VIEW_JOBS',
  EDIT_JOBS = 'EDIT_JOBS',
  DELETE_JOBS = 'DELETE_JOBS',
  ASSIGN_WORKERS = 'ASSIGN_WORKERS',
  MANAGE_WORKERS = 'MANAGE_WORKERS',
  MANAGE_CUSTOMERS = 'MANAGE_CUSTOMERS',
}
